version: '3.8'

services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    ports:
      - "9000:9000"
      - "8812:8812"
    volumes:
      - questdb-data:/root/.questdb

  test:
    build: .
    container_name: test
    depends_on:
      - questdb
    volumes:
      - .:/app
    working_dir: /app

volumes:
  questdb-data:

